# Classificadores

In [13]:
from sklearn.datasets import load_digits, load_breast_cancer, load_wine

#Digits
digits = load_digits()
xdig, ydig = digits.data, digits.target

#Breast Cancer
breast_cancer = load_breast_cancer()
xbre, ybre = breast_cancer.data, breast_cancer.target

#Wine
wine = load_wine()
xwine, ywine = wine.data, wine.target



In [14]:
#Digits
print("Digits: ")
print(xdig[1])
print("----------------------------------")

#Breast Cancer
print("Breast Cancer: ")
print(xbre[1])
print("----------------------------------")

#Wine
print("Wine: ")
print(xwine[1])
print("----------------------------------")

Digits: 
[ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
  3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
 16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
  0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]
----------------------------------
Breast Cancer: 
[2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
 7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
 5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
 2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
 2.750e-01 8.902e-02]
----------------------------------
Wine: 
[1.32e+01 1.78e+00 2.14e+00 1.12e+01 1.00e+02 2.65e+00 2.76e+00 2.60e-01
 1.28e+00 4.38e+00 1.05e+00 3.40e+00 1.05e+03]
----------------------------------


In [15]:
#Digits
print("Digits: ")
print(ydig)
print("----------------------------------")
#Breast Cancer
print("Breast Cancer: ")
print(ybre)
print("----------------------------------")
#Wine
print("Wine: ")
print(ywine)
print("----------------------------------")

Digits: 
[0 1 2 ... 8 9 8]
----------------------------------
Breast Cancer: 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1

In [16]:
results_dig = {}
results_bre = {}
results_wine = {}

# DecisionTree
#However scikit-learn implementation does not support categorical variables for now

In [17]:
from sklearn.tree import DecisionTreeClassifier

clf_tree = DecisionTreeClassifier(random_state=0)

In [18]:
from sklearn.model_selection import cross_val_score

#Digits
print("Digits: ")
scores_dig = cross_val_score(clf_tree, xdig, ydig, cv=3, scoring='f1_weighted')
print(scores_dig)
print("----------------------------------")
#Breast Cancer
print("Breast Cancer: ")
scores_bre = cross_val_score(clf_tree, xbre, ybre, cv=3, scoring='f1_weighted')
print(scores_bre)
print("----------------------------------")
#Wine
print("Wine: ")
scores_wine = cross_val_score(clf_tree, xwine, ywine, cv=3, scoring='f1_weighted')
print(scores_wine)
print("----------------------------------")

Digits: 
[0.74453567 0.81254834 0.75393027]
----------------------------------
Breast Cancer: 
[0.88962696 0.94184084 0.8646422 ]
----------------------------------
Wine: 
[0.77468631 0.83042814 0.93163825]
----------------------------------


In [19]:
import numpy as np

results_dig["tree"] = np.mean(scores_dig)
results_bre["tree"] = np.mean(scores_bre)
results_wine["tree"] = np.mean(scores_wine)

In [20]:
from sklearn.model_selection import cross_validate

scores_dig = cross_validate(clf_tree, xdig, ydig, cv=3, scoring=('f1_weighted', 'precision_weighted', 'recall_weighted'), return_train_score=True)
scores_bre = cross_validate(clf_tree, xbre, ybre, cv=3, scoring=('f1_weighted', 'precision_weighted', 'recall_weighted'), return_train_score=True)
scores_wine = cross_validate(clf_tree, xwine, ywine, cv=3, scoring=('f1_weighted', 'precision_weighted', 'recall_weighted'), return_train_score=True)

In [21]:
print("Digits: ")
print('test_f1_weighted')
print(np.mean(scores_dig['test_f1_weighted']),scores_dig['test_f1_weighted'])
print()

print('test_precision_weighted')
print(np.mean(scores_dig['test_precision_weighted']),scores_dig['test_precision_weighted'])
print()

print('test_recall_weighted')
print(np.mean(scores_dig['test_recall_weighted']),scores_dig['test_recall_weighted'])
print("----------------------------------")

print("Breast Cancer: ")
print('test_f1_weighted')
print(np.mean(scores_bre['test_f1_weighted']),scores_bre['test_f1_weighted'])
print()

print('test_precision_weighted')
print(np.mean(scores_bre['test_precision_weighted']),scores_bre['test_precision_weighted'])
print()

print('test_recall_weighted')
print(np.mean(scores_bre['test_recall_weighted']),scores_bre['test_recall_weighted'])
print("----------------------------------")

print("Wine: ")
print('test_f1_weighted')
print(np.mean(scores_wine['test_f1_weighted']),scores_wine['test_f1_weighted'])
print()

print('test_precision_weighted')
print(np.mean(scores_wine['test_precision_weighted']),scores_wine['test_precision_weighted'])
print()

print('test_recall_weighted')
print(np.mean(scores_wine['test_recall_weighted']),scores_wine['test_recall_weighted'])
print("----------------------------------")

Digits: 
test_f1_weighted
0.7703380959648253 [0.74453567 0.81254834 0.75393027]

test_precision_weighted
0.7769341419978434 [0.74868978 0.82067877 0.76143387]

test_recall_weighted
0.7707289927657207 [0.74457429 0.8130217  0.75459098]
----------------------------------
Breast Cancer: 
test_f1_weighted
0.8987033350306769 [0.88962696 0.94184084 0.8646422 ]

test_precision_weighted
0.9047952506451478 [0.88983175 0.94208242 0.88247158]

test_recall_weighted
0.8980042699340944 [0.88947368 0.94210526 0.86243386]
----------------------------------
Wine: 
test_f1_weighted
0.8455842322485002 [0.77468631 0.83042814 0.93163825]

test_precision_weighted
0.8717270278009318 [0.79995706 0.88186954 0.93335448]

test_recall_weighted
0.8486817325800375 [0.78333333 0.83050847 0.93220339]
----------------------------------


In [22]:
print("Digits: ")
print('train_f1_weighted')
print(np.mean(scores_dig['train_f1_weighted']),scores_dig['train_f1_weighted'])

print('train_precision_weighted')
print(np.mean(scores_dig['train_precision_weighted']),scores_dig['train_precision_weighted'])

print('train_recall_weighted')
print(np.mean(scores_dig['train_recall_weighted']),scores_dig['train_recall_weighted'])
print("----------------------------------")

print("Breast Cancer: ")
print('train_f1_weighted')
print(np.mean(scores_bre['train_f1_weighted']),scores_bre['train_f1_weighted'])

print('train_precision_weighted')
print(np.mean(scores_bre['train_precision_weighted']),scores_bre['train_precision_weighted'])

print('train_recall_weighted')
print(np.mean(scores_bre['train_recall_weighted']),scores_bre['train_recall_weighted'])
print("----------------------------------")

print("Wine: ")
print('train_f1_weighted')
print(np.mean(scores_wine['train_f1_weighted']),scores_wine['train_f1_weighted'])

print('train_precision_weighted')
print(np.mean(scores_wine['train_precision_weighted']),scores_wine['train_precision_weighted'])

print('train_recall_weighted')
print(np.mean(scores_wine['train_recall_weighted']),scores_wine['train_recall_weighted'])
print("----------------------------------")

Digits: 
train_f1_weighted
1.0 [1. 1. 1.]
train_precision_weighted
1.0 [1. 1. 1.]
train_recall_weighted
1.0 [1. 1. 1.]
----------------------------------
Breast Cancer: 
train_f1_weighted
1.0 [1. 1. 1.]
train_precision_weighted
1.0 [1. 1. 1.]
train_recall_weighted
1.0 [1. 1. 1.]
----------------------------------
Wine: 
train_f1_weighted
1.0 [1. 1. 1.]
train_precision_weighted
1.0 [1. 1. 1.]
train_recall_weighted
1.0 [1. 1. 1.]
----------------------------------


In [23]:
#Digits
model_trees_dig = clf_tree.fit(xdig, ydig)
#Breast Cancer
model_trees_bre = clf_tree.fit(xbre, ybre)
#Wine
model_trees_wine = clf_tree.fit(xwine, ywine)

In [12]:

print("Digits: ")
model_trees_dig.predict(xdig, True)
print("----------------------------------")

print("Breast Cancer: ")
model_trees_bre.predict(xbre, True)
print("----------------------------------")

print("Wine: ")
model_trees_wine.predict(xwine, True)
print("----------------------------------")


Digits: 


ValueError: X has 64 features, but DecisionTreeClassifier is expecting 13 features as input.

In [ ]:
model_trees_dig.predict_proba_proba([[2., 2., 3., 3.]])


print("Digits: ")
model_trees_dig.predict_proba([[2., 2., 3., 3.]])
print("----------------------------------")

print("Breast Cancer: ")
model_trees_bre.predict_proba([[2., 2., 3., 3.]])
print("----------------------------------")

print("Wine: ")
model_trees_wine.predict_proba([[2., 2., 3., 3.]])
print("----------------------------------")

In [ ]:
#Digits
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure()
plt.rcParams["figure.figsize"] = (20,20)
plot_tree(model_trees_dig, filled=True)
plt.title("Decision tree trained on all the digits features")
plt.show()

In [ ]:
#Breast Cancer
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure()
plt.rcParams["figure.figsize"] = (20,20)
plot_tree(model_trees_bre, filled=True)
plt.title("Decision tree trained on all the Breast_Cancer features")
plt.show()

In [ ]:
#Wine
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure()
plt.rcParams["figure.figsize"] = (20,20)
plot_tree(model_trees_wine, filled=True)
plt.title("Decision tree trained on all the Wine features")
plt.show()

In [ ]:
#Digits
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini', 'entropy'], 'max_depth':[3, 7, 9]}
best_tree_dig = GridSearchCV(clf_tree, param_grid, scoring=('f1_weighted'), cv=3, refit=True)
best_tree_dig.fit(xdig, ydig)


In [ ]:
#Breast Cancer
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini', 'entropy'], 'max_depth':[3, 7, 9]}
best_tree_bre = GridSearchCV(clf_tree_bre, param_grid, scoring=('f1_weighted'), cv=3, refit=True)
best_tree_bre.fit(xbre, ybre)

In [ ]:
#Wine
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini', 'entropy'], 'max_depth':[3, 7, 9]}
best_tree_wine = GridSearchCV(clf_tree_wine, param_grid, scoring=('f1_weighted'), cv=3, refit=True)
best_tree_wine.fit(xwine, ywine)

# Digits

In [ ]:
import pandas as pd

df_dig = pd.DataFrame(best_tree_dig.cv_results_)
df_dig

In [ ]:
best_model_dig = best_tree_dig.best_estimator_
best_model_dig.fit(xdig, ydig)

df_dig = pd.DataFrame(best_tree_dig.cv_results_)
df_dig

In [ ]:
print(best_tree_dig.cv_results_['mean_test_score'])
print(best_tree_dig.best_estimator_)
print(best_tree_dig.best_params_)
print(best_tree_dig.best_score_)

# Breast_Cancer

In [ ]:
import pandas as pd

df_bre = pd.DataFrame(best_tree_bre.cv_results_)
df_bre

In [ ]:
best_model_bre = best_tree_bre.best_estimator_
best_model_bre.fit(xbre, ybre)

df_bre = pd.DataFrame(best_tree_bre.cv_results_)
df_bre

In [ ]:
print(best_tree_bre.cv_results_['mean_test_score'])
print(best_tree_bre.best_estimator_)
print(best_tree_bre.best_params_)
print(best_tree_bre.best_score_)

# Wine

In [ ]:
import pandas as pd

df_dig = pd.DataFrame(best_tree_dig.cv_results_)
df_dig

In [ ]:
best_model_wine = best_tree_wine.best_estimator_
best_model_wine.fit(xwine, ywine)

df_wine = pd.DataFrame(best_tree_wine.cv_results_)
df_wine

In [ ]:
print(best_tree_wine.cv_results_['mean_test_score'])
print(best_tree_wine.best_estimator_)
print(best_tree_wine.best_params_)
print(best_tree_wine.best_score_)

# Seleção e avaliação no teste

# Digits

In [ ]:
from sklearn.model_selection import train_test_split

X_train_dig, X_test_dig, y_train_dig, y_test_dig = train_test_split(xdig, ydig, test_size=0.3, random_state=0)

param_grid_dig = {'criterion':['gini', 'entropy'], 'max_depth':[3, 7, 9]}
best_tree_dig = GridSearchCV(clf_tree, param_grid_dig, scoring=('f1_weighted'), cv=3)
best_tree_dig.fit(X_train_dig, y_train_dig)

In [ ]:
df_dig = pd.DataFrame(best_tree_dig.cv_results_)
df_dig

In [ ]:
print(best_tree_dig.cv_results_['mean_test_score'])
print(best_tree_dig.best_estimator_)
print(best_tree_dig.best_params_)
print(best_tree_dig.best_score_)

In [ ]:
from sklearn.metrics import classification_report

y_true_dig, y_pred_dig = y_test_dig, best_tree_dig.predict(X_test_dig)
print(classification_report(y_true_dig, y_pred_dig))

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_true_dig, y_pred_dig, average='weighted')

# Breast Cancer

In [ ]:
X_train_bre, X_test_bre, y_train_bre, y_test_bre = train_test_split(xbre, ybre, test_size=0.3, random_state=0)

param_grid_bre = {'criterion':['gini', 'entropy'], 'max_depth':[3, 7, 9]}
best_tree_bre = GridSearchCV(clf_tree, param_grid_bre, scoring=('f1_weighted'), cv=3)
best_tree_bre.fit(X_train_bre, y_train_bre)

In [ ]:
df_bre = pd.DataFrame(best_tree_bre.cv_results_)
df_bre

In [ ]:
print(best_tree_bre.cv_results_['mean_test_score'])
print(best_tree_bre.best_estimator_)
print(best_tree_bre.best_params_)
print(best_tree_bre.best_score_)

In [ ]:
y_true_bre, y_pred_bre = y_test_bre, best_tree_bre.predict(X_test_bre)
print(classification_report(y_true_bre, y_pred_bre))

In [ ]:
f1_score(y_true_bre, y_pred_bre, average='weighted')

# Wine

In [ ]:
X_train_wine, X_test_wine, y_train_wine, y_test_wine = train_test_split(xwine, ywine, test_size=0.3, random_state=0)

param_grid_wine = {'criterion':['gini', 'entropy'], 'max_depth':[3, 7, 9]}
best_tree_wine = GridSearchCV(clf_tree, param_grid_wine, scoring=('f1_weighted'), cv=3)
best_tree_wine.fit(X_train_wine, y_train_wine)

In [ ]:
df_wine = pd.DataFrame(best_tree_wine.cv_results_)
df_wine

In [ ]:
print(best_tree_wine.cv_results_['mean_test_score'])
print(best_tree_wine.best_estimator_)
print(best_tree_wine.best_params_)
print(best_tree_wine.best_score_)

In [ ]:
y_true_wine, y_pred_wine = y_test_wine, best_tree_wine.predict(X_test_wine)
print(classification_report(y_true_wine, y_pred_wine))

In [ ]:
f1_score(y_true_wine, y_pred_wine, average='weighted')

# k-NN

In [ ]:
#https://scikit-learn.org/stable/modules/neighbors.html#neighbors
#https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

clf_knn = KNeighborsClassifier(n_neighbors=3)
clf_knn.fit(X, y)

scores = cross_val_score(clf_knn, X, y, cv=3, scoring='f1_weighted')
scores

In [ ]:
results["knn"] = np.mean(scores)

In [ ]:
clf_knn.predict([[2., 2., 3., 3.]])

# Naive Bayes

In [ ]:
#https://scikit-learn.org/stable/modules/naive_bayes.html
#https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB

#https://towardsdatascience.com/how-i-was-using-naive-bayes-incorrectly-till-now-part-1-4ed2a7e2212b
#GaussianNB → When you have continuous features
#CategoricalNB →When you have categorical data
#MultinomialNB → Applied to text data

In [26]:
from sklearn.naive_bayes import GaussianNB

clf_nb = GaussianNB()
clf_nb.fit(xdig, ydig)

scoresDig = cross_val_score(clf_nb, xdig, ydig, cv=3, scoring='f1_weighted')
scoresDig

array([0.82409571, 0.80427195, 0.81918411])

In [27]:
clf_nb.fit(xbre, ybre)

scoresBre = cross_val_score(clf_nb, xbre, ybre, cv=3, scoring='f1_weighted')
scoresBre

array([0.91496726, 0.94665313, 0.94723836])

In [28]:
clf_nb.fit(xwine, ywine)

scoresWine = cross_val_score(clf_nb, xwine, ywine, cv=3, scoring='f1_weighted')
scoresWine

array([0.94937951, 0.96591585, 0.96612946])

In [29]:
results["nb"] = np.mean(scores)

NameError: name 'results' is not defined

In [30]:
clf_nb.predict([[2., 2., 3., 3.]])

ValueError: operands could not be broadcast together with shapes (1,4) (13,) 

# SVM

In [ ]:
#https://scikit-learn.org/stable/modules/svm.html#svm
#SVC and NuSVC implement the “one-versus-one” approach for multi-class classification.
#https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC

In [ ]:
from sklearn.svm import SVC

clf_svm = SVC()
clf_svm.fit(X, y)

scores = cross_val_score(clf_svm, X, y, cv=3, scoring='f1_weighted')
scores

In [ ]:
results["svm"] = np.mean(scores)

In [ ]:
clf_svm.predict([[2., 2., 3., 3.]])

In [ ]:
# get support vectors
print(clf_svm.support_vectors_)

# get indices of support vectors
print(clf_svm.support_)

# get number of support vectors for each class
print(clf_svm.n_support_)

# MLP CLASSIFIER

In [ ]:
#https://scikit-learn.org/stable/modules/neural_networks_supervised.html#neural-networks-supervised
#https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier


In [ ]:
#Class MLPClassifier implements a multi-layer perceptron (MLP) algorithm that trains using Backpropagation.
#Currently, MLPClassifier supports only the Cross-Entropy loss function, which allows probability estimates by running the predict_proba method.
#MLP trains using Backpropagation. More precisely, it trains using some form of gradient descent and the gradients are calculated using Backpropagation.
#MLPClassifier supports multi-class classification by applying Softmax as the output function.


In [37]:
from sklearn.neural_network import MLPClassifier

#3 camadas intermediárias, uma com 50, a outra com 30 e a outra com 20
clf_mlp = MLPClassifier(hidden_layer_sizes=(50, 30, 10), max_iter=5000, random_state=0)
clf_mlp.fit(xdig, ydig)

scoresDig = cross_val_score(clf_mlp, xdig, ydig, cv=3, scoring='f1_weighted')
scoresDig

array([0.92218953, 0.91016275, 0.89276324])

In [38]:
clf_mlp.fit(xbre, ybre)

scoresBre = cross_val_score(clf_mlp, xbre, ybre, cv=3, scoring='f1_weighted')
scoresBre

array([0.91981979, 0.94685454, 0.92074892])

In [39]:
clf_mlp.fit(xwine, ywine)

scoresWine = cross_val_score(clf_mlp, xwine, ywine, cv=3, scoring='f1_weighted')
scoresWine

array([0.31062271, 0.36916868, 0.40886571])

In [40]:
results["ann"] = np.mean(scores)

NameError: name 'results' is not defined

In [41]:
clf_mlp.predict([[2., 2., 3., 3.]])

ValueError: X has 4 features, but MLPClassifier is expecting 13 features as input.

# Ensemble (??? Não consta  no documento acho que não é necessário)

In [ ]:
#https://scikit-learn.org/stable/modules/ensemble.html#ensemble
#https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html#sklearn.ensemble.AdaBoostClassifier
#https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html#sklearn.ensemble.BaggingClassifier
#https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier


In [ ]:
from sklearn.ensemble import AdaBoostClassifier

clf_AdaB = AdaBoostClassifier()
clf_AdaB.fit(X, y)

scores = cross_val_score(clf_AdaB, X, y, cv=3, scoring='f1_weighted')
scores

In [ ]:
results["AdaB"] = np.mean(scores)

In [ ]:
clf_AdaB.predict([[2., 2., 3., 3.]])

In [ ]:
#e assim sucessivamente...

# Resultados-Finais

In [ ]:
for key, value in results.items():
    print(key, value)